# Site Settings
title: My GitHub Pages Site
description: A personal blog built using GitHub Pages.
author: Your Name
email: your.email@example.com
baseurl: "" # Leave blank unless the site is not at the root of the domain
url: "https://your-username.github.io" # Your GitHub Pages site URL

# Theme
theme: minima # Replace with your preferred Jekyll theme

# Social Links (optional)
social_links:
  - name: GitHub
    url: https://github.com/your-username
  - name: Twitter
    url: https://twitter.com/your-handle

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files or directories from the site
exclude:
  - README.md
  - node_modules/
  - Gemfile
  - Gemfile.lock
