# Site Settings
title: Connor Howe
description: A personal blog built using GitHub Pages.
author: Connor Howe
email: howe0427@umn.edu
baseurl: "" # Leave blank unless the site is not at the root of the domain
url: "https://cwhowe.github.io" # Your GitHub Pages site URL

# Theme
theme: minima # Replace with your preferred Jekyll theme

# Social Links (optional)
social_links:
  - name: GitHub
    url: https://github.com/cwhowe

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files or directories from the site
exclude:
  - README.md
